#!/bin/bash
# Check if dir exists and create if not
[ ! -d "$HOME/RECYCLE" ] && mkdir $HOME/RECYCLE
# Check if file exists and exit if not
[ ! -b "$1" ] && echo "$1: file not exists" && exit
# GZip file and move it to bin
gzip $1 && mv $1.gz $HOME/RECYCLE
# Check for files which lifetime in seconds is
# greater than LIFETIME
find $HOME/RECYCLE/ -atime +6 -delete
