#!/bin/bash
LIFETIME=1
#$(bc <<< 7*24*60*60)
[ ! -d "$HOME/RECYCLE" ] && mkdir $HOME/RECYCLE
gzip $1 && mv $1.gz $HOME/RECYCLE 
for file in $HOME/RECYCLE/*; do
    if [ "$(expr $(date +%s) - $(stat -c %Z $file))" -gt "$LIFETIME" ]; then
        rm $file
    fi
done
